name: 'user-web'
port: 8022
user_srv:
  host: '127.0.0.1'
  port: 50051
jwt:
  key: 'enjqGcSUpig8KCyGH5RJsyLdOmb3BKUr'
sms:
  key: 'xxx'
  secret: 'xxx'
  expire: 60
redis:
  host: '127.0.0.1'
  port: 6379
